site_name: Crowd-Kit
repo_url: https://github.com/toloka/crowd-kit
repo_name: toloka/crowd-kit
site_description: Control the quality of your labeled data with the Python tools you already know.
site_author: Toloka
copyright: Copyright &copy; 2020&ndash;2024 Crowd-Kit Team Authors
theme:
  name: material
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://www.attrs.org/en/stable/objects.inv
        - https://pandas.pydata.org/docs/objects.inv
        - https://pytorch.org/docs/stable/objects.inv
